name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
             SplinterTn
