name: Example Action on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run an example script
        run: |
          echo "Hello from PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}